<script setup>
import { Head, Link } from '@inertiajs/vue3';
import Navbar from '@/components/Navbar.vue';
import {onMounted, ref} from "vue";

defineProps({
    canLogin: {
        type: Boolean,
    },
    canRegister: {
        type: Boolean,
    },
    laravelVersion: {
        type: String,
        required: true,
    },
    phpVersion: {
        type: String,
        required: true,
    },
    isAuthenticated: {  // Assume this prop tells us if the user is authenticated
        type: Boolean,
        required: true,
    }
});

const profileQuestionsUrl = '/form/profile';
const jobDescriptionQuestionsUrl = '/form/job-description';

const typingComplete = ref(false);
const typedText = ref('');
const fullText = 'InterviewArenaAI';
const typingSpeed = 300;  // Speed in milliseconds.

onMounted(() => {
    let charIndex = 0;
    const typeInterval = setInterval(() => {
        typedText.value += fullText[charIndex];
        charIndex++;
        if (charIndex === fullText.length) {
            clearInterval(typeInterval);
            typingComplete.value = true;  // Set this to true once the typing is done.
        }
    }, typingSpeed);
});

</script>

<template>
    <Head title="Welcome" />
    <div class="bg-muddy-white">
        <Navbar></Navbar>
        <!--Hero section-->
        <div class="container mx-auto py-10 sm:py-20 p-6 sm:p-12 flex flex-col sm:flex-row font-raleway">
            <!-- Text Section -->
            <div class="sm:w-1/2 mt-4 sm:mt-16 text-center sm:text-left">
                <h1 class="text-3xl sm:text-5xl mb-2 sm:mb-4">Welcome to <span class="text-blue-welcome font-black">{{ typedText }}</span><span v-if="!typingComplete"  class="typing-cursor">|</span>,</h1>
                <h2 class="text-3xl sm:text-5xl mb-4 sm:mb-6">your AI generated interview space</h2>
                <p class="text-gray-600 mb-4 sm:mb-8 font-medium">Prepare for interviews with real job questions generated by AI and get instant feedback. Just select your target job and we will do the rest.</p>
                <button class="bg-blue-500 text-white px-4 sm:px-8 py-2 sm:py-3 rounded-lg">Start Interview</button>
            </div>

            <!-- Illustration Section -->
            <div class="sm:w-1/2 flex justify-center mt-6 sm:mt-0">
                <img class="w-8/12 sm:w-2/3" src="img/left-illustration-2.png" alt="Illustration">
            </div>
        </div>
        <!--Messages section-->
        <div class="container mx-auto mt-8 sm:mt-16 p-4 sm:p-12 font-raleway">
            <div class="bg-blue-welcome p-4 sm:p-10 rounded-3xl">
                <h2 class="text-2xl sm:text-4xl font-black p-4 sm:p-8 mb-4 sm:mb-6 text-white text-center">Why choose InterviewArenaAI for your interview preparation?</h2>

                <!-- Message 1 (Starting from left) -->
                <div class="flex flex-col sm:flex-row items-start mb-4 relative">
                    <div class="message-bubble-left p-4 bg-white rounded-lg max-w-2xl flex items-start shadow-2xl relative mx-auto sm:mx-0">
                        <img src="img/png/message_1.png" alt="Icon 1" class="mt-3 w-10 sm:w-16 h-10 sm:h-16 mr-4">
                        <div>
                            <h3 class="text-lg sm:text-xl font-semibold mb-2">Personalized Interview Questions</h3>
                            <p class="text-md sm:text-lg">We provide personalized questions based on your unique profile or job description, helping you prepare effectively and stand out in interviews.</p>
                        </div>
                    </div>
                </div>

                <!-- Message 2 (Starting from right) -->
                <div class="flex flex-col sm:flex-row items-start mb-4 justify-end relative">
                    <div class="message-bubble-right p-4 bg-white rounded-lg max-w-2xl flex items-start shadow-2xl relative mx-auto sm:mx-0">
                        <img src="img/png/message_2.png" alt="Icon 2" class="mt-3 w-10 sm:w-16 h-10 sm:h-16 mr-4">
                        <div>
                            <h3 class="text-lg sm:text-xl font-semibold mb-2">Quick, AI-Driven Feedback</h3>
                            <p class="text-md sm:text-lg">Receive instant, AI-driven feedback on your answers, allowing you to identify and improve on your weaknesses, enhancing your interview skills.</p>
                        </div>
                    </div>
                </div>

                <!-- Message 3 (Starting from left) -->
                <div class="flex flex-col sm:flex-row items-start mb-4 relative">
                    <div class="message-bubble-left p-4 bg-white rounded-lg max-w-2xl flex items-start shadow-2xl relative mx-auto sm:mx-0">
                        <img src="img/png/message_3.png" alt="Icon 3" class="mt-3 w-10 sm:w-16 h-10 sm:h-16 mr-4">
                        <div>
                            <h3 class="text-lg sm:text-xl font-semibold mb-2">Secure and Private Preparation Platform</h3>
                            <p class="text-md sm:text-lg">Your data and preparation materials are kept secure and private, ensuring your peace of mind as you prepare for your interviews with InterviewArena.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--How it's working section-->
        <div class="container mx-auto mt-10 sm:mt-20 p-4 sm:p-8">
            <!-- Title -->
            <h2 class="text-center text-2xl sm:text-3xl font-bold mb-6 sm:mb-10">How does InterviewArenaAI work?</h2>

            <!-- Cards Grid -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-8">
                <!-- Card 1 -->
                <div class="bg-white p-4 sm:p-6 rounded-xl shadow-xl text-center">
                    <div class="mb-3 sm:mb-4">
                        <span class="text-4xl sm:text-5xl text-gray-400">1</span>
                    </div>
                    <div class="mb-4 sm:mb-6">
                        <img src="img/png/message_4.png" alt="Profile Description" class="mx-auto w-20 sm:w-24 h-20 sm:h-24">
                    </div>
                    <p class="font-medium text-md sm:text-lg mb-3 sm:mb-4">
                        Start by filling in your profile or a job description. This information allows us to generate personalized interview questions tailored to your specific needs and goals.
                    </p>
                </div>

                <!-- Card 2 -->
                <div class="bg-white p-4 sm:p-6 rounded-xl shadow-xl text-center">
                    <div class="mb-3 sm:mb-4">
                        <span class="text-4xl sm:text-5xl text-gray-400">2</span>
                    </div>
                    <div class="mb-4 sm:mb-6">
                        <img src="img/png/message_5.png" alt="Advanced AI" class="mx-auto w-20 sm:w-24 h-20 sm:h-24">
                    </div>
                    <p class="font-medium text-md sm:text-lg mb-3 sm:mb-4">
                        Our advanced AI analyzes the data to generate relevant and challenging questions that help you prepare for real-world interviews, ensuring you are ready for any question.
                    </p>
                </div>

                <!-- Card 3 -->
                <div class="bg-white p-4 sm:p-6 rounded-xl shadow-xl text-center">
                    <div class="mb-3 sm:mb-4">
                        <span class="text-4xl sm:text-5xl text-gray-400">3</span>
                    </div>
                    <div class="mb-4 sm:mb-6">
                        <img src="img/png/message_6.png" alt="AI Feedback" class="mx-auto w-20 sm:w-24 h-20 sm:h-24">
                    </div>
                    <p class="font-medium text-md sm:text-lg mb-3 sm:mb-4">
                        Practice answering the questions and receive instant feedback from our AI. This feedback helps you understand your strengths and weaknesses, allowing you to improve your answers and increase your chances of interview success.
                    </p>
                </div>
            </div>
        </div>
        <!--Brands section-->
        <div class="container mx-auto mt-8 sm:mt-12 p-4 sm:p-8">
            <div class="text-center">
                <p class="text-gray-600 mb-8 sm:mb-10 text-3xl sm:text-4xl font-black">Some companies our members got hired at:</p>

                <div class="grid grid-cols-2 sm:grid-cols-4 gap-6 sm:gap-10 mb-6 sm:mb-10">
                    <img src="img/png/google.png" alt="Google" class="h-24 sm:h-32 mx-auto">

                    <img src="img/png/uber.png" alt="Uber" class="h-24 sm:h-32 mx-auto">

                    <img src="img/png/microsoft.png" alt="Microsoft" class="h-20 sm:h-24 mx-auto mt-4 sm:mt-0">

                    <img src="img/png/meta.png" alt="Meta" class="h-24 sm:h-32 mx-auto">
                </div>

                <div class="grid grid-cols-2 sm:grid-cols-2 gap-6 sm:gap-10">
                    <img src="img/png/tesla.png" alt="Tesla" class="h-24 sm:h-32 mx-auto">

                    <img src="img/png/netflix.png" alt="Netflix" class="h-16 sm:h-20 mx-auto mt-6 sm:mt-8">
                </div>
            </div>
        </div>
        <!--Testimonials section-->
        <div class="container mx-auto px-4 sm:px-8 md:px-16 lg:px-32 py-16">
            <div class="bg-blue-welcome p-6 sm:p-8 rounded-3xl">
                <h1 class="text-center text-white text-2xl sm:text-3xl mt-6 sm:mt-12 mb-4 sm:mb-8 font-black font-raleway">What our members say?</h1>
                <div class="grid grid-cols-1 md:grid-cols-3 gap-6 p-4 sm:p-6">
                    <!-- Example Card -->
                    <div class="bg-white p-4 rounded-3xl shadow-2xl text-center">
                        <img src="img/png/user1.png" alt="Jessica R." class="w-32 sm:w-44 h-32 sm:h-44 mx-auto rounded-full mt-4 sm:mt-6 mb-4">
                        <h2 class="font-black text-lg sm:text-xl mb-2">Jessica R.</h2>
                        <div class="flex justify-center mb-4">
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                        </div>
                        <p class="text-sm sm:text-base">InterviewArena's AI tool transformed my job prep! Tailored questions for my role were key. It's the ultimate interview ace!</p>
                    </div>
                    <!-- End of Example Card -->
                    <!-- Testimonial for Jane S. -->
                    <div class="bg-white p-4 rounded-3xl shadow-2xl text-center">
                        <img src="img/png/user2.png" alt="David S." class="w-32 sm:w-44 h-32 sm:h-44 mx-auto rounded-full mt-4 sm:mt-6 mb-4">
                        <h2 class="font-black text-lg sm:text-xl mb-2">David S.</h2>
                        <div class="flex justify-center mb-4">
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                        </div>
                        <p class="text-sm sm:text-base">Thanks to InterviewArenaAI, I felt confident in every interview. The AI-driven insights made me realize where I shine and where I need to work.</p>
                    </div>

                    <!-- Testimonial for the other John D. -->
                    <div class="bg-white p-4 rounded-3xl shadow-2xl text-center">
                        <img src="img/png/user3.png" alt="Samuel D." class="w-32 sm:w-44 h-32 sm:h-44 mx-auto rounded-full mt-4 sm:mt-6 mb-4">
                        <h2 class="font-black text-lg sm:text-xl mb-2">Samuel D.</h2>
                        <div class="flex justify-center mb-4">
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                            <span class="text-yellow-500 text-3xl sm:text-4xl">★</span>
                        </div>
                        <p class="text-sm sm:text-base">Being in the tech industry, I've seen many tools, but none like this. InterviewArenaAI truly gets how to prepare someone for the challenges ahead.</p>
                    </div>

                    <!-- Repeat for other testimonials using the same structure -->
                </div>
            </div>
        </div>

        <footer class="bg-blue-footer text-white py-12 px-8">
            <div class="container mx-auto flex flex-wrap md:flex-nowrap justify-between items-start space-y-8 md:space-y-0">

                <!-- Logo -->
                <div class="mb-8 md:mb-0">
                    <h1 class="text-3xl font-bold">InterviewArenaAI</h1>
                </div>

                <!-- Quick Links -->
                <div class="w-full md:w-1/3">
                    <h2 class="text-xl mb-4 font-semibold">Quick Links</h2>
                    <ul>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">Terms of Service</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">Privacy Policy</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">FAQ</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">Contact</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">About us</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">Buy Tokens</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">Subscriptions</a></li>
                        <li class="mb-2"><a href="#" class="hover:text-gray-300">News</a></li>
                    </ul>
                </div>

                <!-- Newsletter -->
                <div class="w-full md:w-1/3 bg-white p-8 rounded-lg">
                    <h2 class="text-xl mb-4 text-black font-semibold">Join Our Newsletter</h2>
                    <p class="mb-6 text-black">Stay up to date with our latest updates and offers!</p>
                    <form action="#">
                        <input type="email" placeholder="Email" class="mb-4 w-full px-4 py-2 rounded bg-white text-black">
                        <hr>
                        <br>
                        <button type="submit" class="w-full py-2 bg-red-600 rounded text-white">Sign me up</button>
                    </form>
                    <p class="mt-4 text-sm">By signing up you agree to our terms and services.</p>
                </div>
            </div>

            <!-- Copyright -->
            <div class="text-center mt-8 text-sm">
                © 2023 InterviewArena - All rights reserved
            </div>
        </footer>

    </div>
</template>

<style>
.message-bubble-left::before {
    content: '';
    width: 0;
    height: 0;
    border-left: 12px solid transparent;
    border-right: 12px solid white;
    border-top: 12px solid white;
    border-bottom: 0;
    position: absolute;
    left: -12px;
    top: 0;
}

.message-bubble-right::before {
    content: '';
    width: 0;
    height: 0;
    border-left: 12px solid white;
    border-right: 12px solid transparent;
    border-top: 12px solid white;
    border-bottom: 0;
    position: absolute;
    right: -12px; /* This positions the notch on the right side */
    top: 0;
}
.typing-cursor {
    display: inline-block;
    animation: blink 1s infinite;
}

@keyframes blink {
    0%, 49% {
        opacity: 1;
    }
    50%, 100% {
        opacity: 0;
    }
}
</style>
